from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
import logging
from engine.utils import load_config

cfg = load_config()

def generate_pdf_summary(out_path, client_name, summary_dict):
    c = canvas.Canvas(out_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(30*mm, (height - 30*mm), f"Reconciliation Summary — {client_name}")

    c.setFont("Helvetica", 11)
    y = height - 45*mm
    for k,v in summary_dict.items():
        c.drawString(30*mm, y, f"{k}: {v}")
        y -= 8*mm

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(30*mm, 20*mm, f"Generated by {cfg["app"].get("name", "")}")

    c.showPage()
    c.save()
    logging.info(f"PDF summary saved to {out_path}")
    return out_path
